export const ADD_CARD_LIST_ITEM = 'ADD_CARD_LIST_ITEM';
export const REMOVE_CARD_LIST_ITEM = 'REMOVE_CARD_LIST_ITEM';
export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';

export const FETCH_CARDS_PENDING = 'FETCH_CARDS_PENDING';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_ERROR = 'FETCH_CARDS_ERROR';
